import { CelestialBodyData } from './types';

export const SOLAR_SYSTEM_DATA: CelestialBodyData[] = [
  {
    id: 'sun',
    name: 'Sun',
    type: 'star',
    radius: 696340,
    distanceFromParent: 0,
    orbitalPeriod: 0,
    rotationPeriod: 609.6,
    color: '#ffcc33',
    textureUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/99/Map_of_the_full_sun.jpg',
    description: 'The Sun is the star at the center of the Solar System. It is a nearly perfect sphere of hot plasma, heated to incandescence by nuclear fusion reactions in its core.',
  },
  {
    id: 'mercury',
    name: 'Mercury',
    type: 'planet',
    radius: 2439.7,
    distanceFromParent: 57.9,
    orbitalPeriod: 88,
    rotationPeriod: 1407.6,
    eccentricity: 0.205,
    color: '#A5A5A5',
    textureUrl: 'https://raw.githubusercontent.com/mrdoob/three.js/master/examples/textures/planets/mercury.jpg',
    description: 'Mercury is the smallest planet in the Solar System and the closest to the Sun. Its orbit around the Sun takes 87.97 Earth days, the shortest of all the Sun\'s planets.',
  },
  {
    id: 'venus',
    name: 'Venus',
    type: 'planet',
    radius: 6051.8,
    distanceFromParent: 108.2,
    orbitalPeriod: 224.7,
    rotationPeriod: -5832.5, // Retrograde
    eccentricity: 0.007,
    color: '#E3BB76',
    textureUrl: 'https://raw.githubusercontent.com/mrdoob/three.js/master/examples/textures/planets/venus_surface.jpg',
    description: 'Venus is the second planet from the Sun. It is sometimes called Earth\'s "sister" or "twin" planet as it is almost as large and has a similar composition.',
    atmosphere: {
      color: '#E3BB76',
      opacity: 0.8,
      cloudsUrl: 'https://raw.githubusercontent.com/mrdoob/three.js/master/examples/textures/planets/venus_atmosphere.jpg',
    }
  },
  {
    id: 'earth',
    name: 'Earth',
    type: 'planet',
    radius: 6371,
    distanceFromParent: 149.6,
    orbitalPeriod: 365.25,
    rotationPeriod: 23.9,
    eccentricity: 0.017,
    color: '#2233FF',
    textureUrl: 'https://raw.githubusercontent.com/mrdoob/three.js/master/examples/textures/planets/earth_atmos_2048.jpg',
    bumpUrl: 'https://raw.githubusercontent.com/mrdoob/three.js/master/examples/textures/planets/earth_bump_2048.jpg',
    specularUrl: 'https://raw.githubusercontent.com/mrdoob/three.js/master/examples/textures/planets/earth_specular_2048.jpg',
    description: 'Earth is the third planet from the Sun and the only astronomical object known to harbor life. About 71% of Earth\'s surface is covered with water.',
    atmosphere: {
      color: '#4488FF',
      opacity: 0.5,
      cloudsUrl: 'https://raw.githubusercontent.com/mrdoob/three.js/master/examples/textures/planets/earth_clouds_2048.jpg',
    },
    moons: [
      {
        id: 'moon',
        name: 'Moon',
        type: 'moon',
        radius: 1737.4,
        distanceFromParent: 384400,
        orbitalPeriod: 27.3,
        rotationPeriod: 655.7,
        eccentricity: 0.055,
        color: '#CCCCCC',
        textureUrl: 'https://raw.githubusercontent.com/mrdoob/three.js/master/examples/textures/planets/moon_1024.jpg',
        description: 'The Moon is Earth\'s only natural satellite. It is the fifth-largest satellite in the Solar System and the largest and most massive relative to its parent planet.',
      }
    ]
  },
  {
    id: 'mars',
    name: 'Mars',
    type: 'planet',
    radius: 3389.5,
    distanceFromParent: 227.9,
    orbitalPeriod: 687,
    rotationPeriod: 24.6,
    eccentricity: 0.093,
    color: '#E27B58',
    textureUrl: 'https://raw.githubusercontent.com/mrdoob/three.js/master/examples/textures/planets/mars.jpg',
    description: 'Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System. It is often referred to as the "Red Planet".',
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    type: 'planet',
    radius: 69911,
    distanceFromParent: 778.6,
    orbitalPeriod: 4333,
    rotationPeriod: 9.9,
    eccentricity: 0.048,
    color: '#D39C7E',
    textureUrl: 'https://raw.githubusercontent.com/mrdoob/three.js/master/examples/textures/planets/jupiter.jpg',
    description: 'Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass more than two and a half times that of all the other planets combined.',
  },
  {
    id: 'saturn',
    name: 'Saturn',
    type: 'planet',
    radius: 58232,
    distanceFromParent: 1433.5,
    orbitalPeriod: 10759,
    rotationPeriod: 10.7,
    eccentricity: 0.056,
    color: '#C5AB6E',
    textureUrl: 'https://raw.githubusercontent.com/mrdoob/three.js/master/examples/textures/planets/saturn.jpg',
    description: 'Saturn is the sixth planet from the Sun and the second-largest in the Solar System. It is a gas giant with an average radius of about nine times that of Earth.',
    rings: {
      innerRadius: 74500,
      outerRadius: 140220,
      textureUrl: 'https://raw.githubusercontent.com/mrdoob/three.js/master/examples/textures/planets/saturn_ring_alpha.png',
    },
    moons: [
      {
        id: 'titan',
        name: 'Titan',
        type: 'moon',
        radius: 2574.7,
        distanceFromParent: 1221870,
        orbitalPeriod: 15.9,
        rotationPeriod: 382.7,
        eccentricity: 0.028,
        color: '#E3BB76',
        textureUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/45/Titan_in_true_color.jpg',
        description: 'Titan is the largest moon of Saturn and the second-largest natural satellite in the Solar System. It is the only moon known to have a dense atmosphere.',
      },
      {
        id: 'rhea',
        name: 'Rhea',
        type: 'moon',
        radius: 763.8,
        distanceFromParent: 527040,
        orbitalPeriod: 4.518,
        rotationPeriod: 108.43,
        eccentricity: 0.001258,
        color: '#CCCCCC',
        textureUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Rhea_full_hemisphere.jpg/1024px-Rhea_full_hemisphere.jpg',
        description: 'Rhea is the second-largest moon of Saturn and the ninth-largest moon in the Solar System.',
      }
    ]
  },
  {
    id: 'uranus',
    name: 'Uranus',
    type: 'planet',
    radius: 25362,
    distanceFromParent: 2872.5,
    orbitalPeriod: 30687,
    rotationPeriod: -17.2, // Retrograde
    eccentricity: 0.046,
    color: '#B5E3E3',
    textureUrl: 'https://raw.githubusercontent.com/mrdoob/three.js/master/examples/textures/planets/uranus.jpg',
    description: 'Uranus is the seventh planet from the Sun. Its name is a reference to the Greek god of the sky, Uranus. It has the third-largest planetary radius and fourth-largest planetary mass.',
    rings: {
      innerRadius: 38000,
      outerRadius: 51149,
      textureUrl: 'https://raw.githubusercontent.com/mrdoob/three.js/master/examples/textures/planets/saturn_ring_alpha.png', // Fallback for alpha
    }
  },
  {
    id: 'neptune',
    name: 'Neptune',
    type: 'planet',
    radius: 24622,
    distanceFromParent: 4495.1,
    orbitalPeriod: 60190,
    rotationPeriod: 16.1,
    eccentricity: 0.011,
    color: '#4B70DD',
    textureUrl: 'https://raw.githubusercontent.com/mrdoob/three.js/master/examples/textures/planets/neptune.jpg',
    description: 'Neptune is the eighth and farthest-known solar planet from the Sun. In the Solar System, it is the fourth-largest planet by diameter, the third-most-massive planet.',
  }
];

export const MINOR_BODIES_DATA: CelestialBodyData[] = [
  // --- Dwarf Planets & KBOs ---
  {
    id: 'pluto',
    name: 'Pluto',
    type: 'dwarf-planet',
    radius: 1188.3,
    distanceFromParent: 5906.4,
    orbitalPeriod: 90560,
    rotationPeriod: -153.3,
    eccentricity: 0.249,
    color: '#C4A882',
    textureUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2a/Nh-pluto-in-true-color_2x_JPEG-edit-frame.jpg',
    description: 'Pluto is a dwarf planet in the Kuiper belt. It was the first Kuiper belt object to be discovered and is the largest known dwarf planet.',
    moons: [
      {
        id: 'charon',
        name: 'Charon',
        type: 'moon',
        radius: 606,
        distanceFromParent: 19591,
        orbitalPeriod: 6.387,
        rotationPeriod: 153.3,
        color: '#8B8B8B',
        textureUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Charon_in_Color_%28HQ%29.jpg',
        description: 'Charon is the largest of the five known natural satellites of Pluto.',
      }
    ]
  },
  {
    id: 'ceres',
    name: 'Ceres',
    type: 'dwarf-planet',
    radius: 473,
    distanceFromParent: 413.7,
    orbitalPeriod: 1682,
    rotationPeriod: 9.074,
    eccentricity: 0.076,
    color: '#8B7D6B',
    textureUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/ab/PIA20916-Ceres-DwarfPlanet-DawnSpacecraft-20160204.jpg',
    description: 'Ceres is the largest object in the asteroid belt and the only dwarf planet in the inner Solar System.',
  },
  {
    id: 'eris',
    name: 'Eris',
    type: 'dwarf-planet',
    radius: 1163,
    distanceFromParent: 10120,
    orbitalPeriod: 203830,
    rotationPeriod: 25.9,
    eccentricity: 0.436,
    color: '#D4C4B0',
    textureUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Eris_and_dysnomia2.jpg',
    description: 'Eris is the most massive and second-largest known dwarf planet.',
  },
  {
    id: 'haumea',
    name: 'Haumea',
    type: 'dwarf-planet',
    radius: 816,
    distanceFromParent: 6452,
    orbitalPeriod: 103774,
    rotationPeriod: 3.915,
    eccentricity: 0.191,
    color: '#E8E0D0',
    textureUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/7e/2003EL61_Haumea_Cropped.jpg',
    description: 'Haumea is a dwarf planet beyond Neptune with a distinctive elongated shape and rapid rotation.',
    rings: {
      innerRadius: 2287,
      outerRadius: 2322,
      textureUrl: 'https://raw.githubusercontent.com/mrdoob/three.js/master/examples/textures/planets/saturn_ring_alpha.png',
    },
  },
  {
    id: 'makemake',
    name: 'Makemake',
    type: 'dwarf-planet',
    radius: 715,
    distanceFromParent: 6850,
    orbitalPeriod: 111845,
    rotationPeriod: 22.8,
    eccentricity: 0.159,
    color: '#D9C8A8',
    textureUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/7d/Makemake_Hubble.jpg',
    description: 'Makemake is a dwarf planet and the second-brightest known object in the Kuiper belt after Pluto.',
  },
  {
    id: 'sedna',
    name: 'Sedna',
    type: 'kbo',
    radius: 497.5,
    distanceFromParent: 76000,
    orbitalPeriod: 4161000,
    rotationPeriod: 10.273,
    eccentricity: 0.855,
    color: '#C44E3A',
    textureUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3c/Sedna-2003VB12.jpg',
    description: 'Sedna is a large minor planet in the outer reaches of the Solar System.',
  },
  {
    id: 'quaoar',
    name: 'Quaoar',
    type: 'kbo',
    radius: 555,
    distanceFromParent: 6520,
    orbitalPeriod: 105560,
    rotationPeriod: 17.678,
    eccentricity: 0.035,
    color: '#A8A8A8',
    textureUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/59/Quaoar-2002lm60.jpg',
    description: 'Quaoar is a large Kuiper belt object with one known moon, Weywot.',
  },
  {
    id: 'orcus',
    name: 'Orcus',
    type: 'kbo',
    radius: 458.5,
    distanceFromParent: 5872,
    orbitalPeriod: 89780,
    rotationPeriod: 13.188,
    eccentricity: 0.227,
    color: '#8B7D6B',
    textureUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/cf/Orcus_art.jpg',
    description: 'Orcus is a large Kuiper belt object sometimes called the anti-Pluto.',
  },
  {
    id: 'gonggong',
    name: 'Gonggong',
    type: 'kbo',
    radius: 615,
    distanceFromParent: 10140,
    orbitalPeriod: 231000,
    rotationPeriod: 44.81,
    eccentricity: 0.501,
    color: '#C8B8A8',
    textureUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/cf/Gonggong_and_Xiangliu.jpg',
    description: 'Gonggong is a large scattered disc object with a highly eccentric orbit.',
  },
  {
    id: 'salacia',
    name: 'Salacia',
    type: 'kbo',
    radius: 423,
    distanceFromParent: 6340,
    orbitalPeriod: 99200,
    rotationPeriod: 5.5,
    eccentricity: 0.106,
    color: '#8B7D6B',
    textureUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Salacia_2003SB313.png',
    description: 'Salacia is a large trans-Neptunian object.',
  },
  // --- Comets ---
  {
    id: 'halley',
    name: "Halley's Comet",
    type: 'comet',
    radius: 11,
    distanceFromParent: 2670,
    orbitalPeriod: 27510,
    rotationPeriod: 171.6,
    eccentricity: 0.967,
    color: '#E8E0D0',
    textureUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/52/Halley%27s_Comet%2C_1910.jpg',
    description: "Halley's Comet is a short-period comet visible from Earth every 75-76 years.",
    tailColor: '#88CCFF',
  },
  {
    id: 'halebopp',
    name: 'Hale-Bopp',
    type: 'comet',
    radius: 30,
    distanceFromParent: 3500,
    orbitalPeriod: 73120,
    rotationPeriod: 11.74,
    eccentricity: 0.995,
    color: '#F0E8D8',
    textureUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Comet_Hale-Bopp_1995O1.jpg',
    description: 'Comet Hale-Bopp was one of the most widely observed comets of the 20th century.',
    tailColor: '#AAEEFF',
  },
  {
    id: 'hyakutake',
    name: 'Hyakutake',
    type: 'comet',
    radius: 2,
    distanceFromParent: 2200,
    orbitalPeriod: 34830,
    rotationPeriod: 6.23,
    eccentricity: 0.999,
    color: '#D8D0C8',
    textureUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Hyakutake-tsukuba.jpg',
    description: 'Comet Hyakutake was a spectacular comet in 1996 that passed very close to Earth.',
    tailColor: '#99DDEE',
  },
];

// --- Asteroid Belt ---
export const ASTEROID_BELT: CelestialBodyData = {
  id: 'asteroid-belt',
  name: 'Asteroid Belt',
  type: 'asteroid-belt',
  radius: 0,
  distanceFromParent: 400,
  orbitalPeriod: 0,
  rotationPeriod: 0,
  color: '#8B8070',
  textureUrl: '',
  description: 'The asteroid belt is a torus-shaped region in the Solar System, located roughly between the orbits of Mars and Jupiter.',
};

export const ALL_BODIES: CelestialBodyData[] = [
  ...SOLAR_SYSTEM_DATA,
  ...MINOR_BODIES_DATA,
  ASTEROID_BELT,
];

// Scale factors for visualization
export const SCALE_FACTORS = {
  PLANET_SIZE: 0.00001, // 1km = 0.00001 units
  DISTANCE: 1.0, // 1 million km = 1.0 units
  TIME: 86400, // 1 Earth day = 86400 seconds (real-time reference)
  VISUAL_ENHANCEMENT: 100, // Multiplier for planet sizes to make them visible
};
